---
user: "{{ vault_user }}"
podman_dir: /home/{{ user }}/.podman
systemd_dir: "/home/{{ user }}/.config/systemd/user"
domain: "{{ vault_domain }}"
nextcloud_version: 27
mysql_password: "{{ vault_mysql_password }}"
mysql_database: "{{ vault_mysql_database }}"
mysql_user: "{{ vault_mysql_user }}"
mysql_root_password: "{{ vault_mysql_root_password }}"
alt_ssh_port: "{{ vault_alt_ssh_port }}"
redis_password: "{{ vault_redis_password }}"
smtp_host: "{{ vault_smtp_host }}"
smtp_secure: "{{ vault_smtp_secure }}"
smtp_port: "{{ vault_smtp_port }}"
smtp_authtype: "{{ vault_smtp_authtype }}"
smtp_name: "{{ vault_smtp_name }}"
smtp_password: "{{ vault_smtp_password }}"
mail_from_address: "{{ vault_mail_from_address }}"
mail_domain: "{{ vault_mail_domain }}"
