---
- name: Add repository
  ansible.builtin.command:
    cmd: dnf config-manager --add-repo "{{ tailscale_repo_url }}"
    creates: /etc/yum.repos.d/tailscale.repo

- name: Install Tailscale
  ansible.builtin.dnf:
    name: tailscale
    update_cache: true
    state: present

- name: Enable Tailscale service
  ansible.builtin.service:
    name: tailscaled
    enabled: true
    state: started

- name: Start Tailscale
  ansible.builtin.command:
    cmd: /usr/bin/tailscale up --authkey "{{ tailscale_key }}"

