---
- name: Restart firewalld service
  ansible.builtin.systemd:
    state: restarted
    name: firewalld

- name: Grant permissions to nextcloud data directory to container user
  become: false
  become_user: :"{{ user }}"
  ansible.builtin.command:
    cmd: podman unshare chown -R 33:33 /mnt/nextcloud-data/data

- name: Grant permissions to mysql_backups directory to container user
  become: false
  become_user: :"{{ user }}"
  ansible.builtin.command:
    cmd: podman unshare chown -R 999:999 /home/{{ user }}/.podman/nextcloud/mysql_backups

- name: Grant permissions to mariadb directory to container user
  become: false
  become_user: :"{{ user }}"
  ansible.builtin.command:
    cmd: podman unshare chown -R 999:999 /home/{{ user }}/.podman/nextcloud/mariadb

- name: Enable lingering
  ansible.builtin.command:
    cmd: loginctl enable-linger {{ user }}
  when:
    - user != "root"

- name: Restart Nextcloud services
  become: true
  become_user: "{{ user }}"
  ansible.builtin.systemd:
    name: "pod-nextcloud-pod.service"
    scope: user
    enabled: true
    state: restarted
  environment:
    XDG_RUNTIME_DIR: /run/user/{{ ansible_user_uid }}
